x-common-config: &common-config
  image: nanobot:latest
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/root/.nanobot
    - ~/coding:/root/coding
    - ~/Downloads:/root/Downloads

services:
  nanobot:
    container_name: nanobot
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
